- github actions: added step to run e2e tests before deploy

diff --git a/.github/workflows/github-actions-ec2.yml b/.github/workflows/github-actions-ec2.yml
--- a/.github/workflows/github-actions-ec2.yml
+++ b/.github/workflows/github-actions-ec2.yml
@@ -15,11 +15,46 @@ jobs:
         uses: actions/checkout@v2
       - name: Add mysql password text file for a test mysql container
         run: echo "password" >> db/mysql_pwd.txt
-      - name: Run backend tests
-        run: sudo ./script.sh run-api-tests
+      # - name: Run backend tests
+      #   run: sudo ./script.sh run-api-tests
+      # - name: Zip allure reports
+      #   if: success() || failure()
+      #   run: cd src/test && mv allure-results results && zip -r results.zip results
+      # - name: Copy zipped reports to allure server
+      #   if: success() || failure()
+      #   uses: appleboy/scp-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     source: "src/test/results.zip"
+      #     target: "/home/ubuntu/allure-docker/projects/backend/"
+      #     strip_components: 2
+      # - name: Delete previous allure-results folder, unzip new one and delete zipped after
+      #   if: success() || failure()
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.HOST_DNS }}
+      #     username: ${{ secrets.USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_KEY }}
+      #     port: 22
+      #     script: >-
+      #       cd /home/ubuntu/allure-docker/projects/backend &&
+      #       sudo rm -rf results &&
+      #       unzip results.zip &&
+      #       rm results.zip &&
+      #       curl http://localhost:5050/allure-docker-service/generate-report?project_id=backend
+      - name: Checkout frontend repo
+        uses: actions/checkout@v3
+        with:
+          repository: mg-login-examples/login-frontend-vue
+          path: frontend
+      - name: Run e2e tests
+        run: sudo ./script.sh run-e2e-tests
       - name: Zip allure reports
         if: success() || failure()
-        run: cd src/test && mv allure-results results && zip -r results.zip results
+        run: cd frontend/tests/e2e && mv allure-results results && zip -r results.zip results
       - name: Copy zipped reports to allure server
         if: success() || failure()
         uses: appleboy/scp-action@master
@@ -28,10 +63,10 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           port: 22
-          source: "src/test/results.zip"
-          target: "/home/ubuntu/allure-docker/projects/backend/"
+          source: "frontend/tests/e2e/results.zip"
+          target: "/home/ubuntu/allure-docker/projects/frontend-e2e/"
           strip_components: 2
-      - name: Delete previous allure-results folder, unzip new one and delete zipped after
+      - name: Delete previous allure-results folder, unzip new results and delete zipped results, and generate report
         if: success() || failure()
         uses: appleboy/ssh-action@master
         with:
@@ -39,14 +74,12 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           port: 22
-          script: cd /home/ubuntu/allure-docker/projects/backend && sudo rm -rf results && unzip results.zip && rm results.zip
-      # - name: Deploy to Server 1
-      #   uses: easingthemes/ssh-deploy@main
-      #   env:
-      #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-      #     REMOTE_HOST: ${{ secrets.HOST_DNS }}
-      #     REMOTE_USER: ${{ secrets.USERNAME }}
-      #     TARGET: ${{ secrets.TARGET_DIR }}
+          script: >-
+            cd /home/ubuntu/allure-docker/projects/frontend-e2e &&
+            sudo rm -rf results &&
+            unzip results.zip &&
+            rm results.zip &&
+            curl http://localhost:5050/allure-docker-service/generate-report?project_id=frontend-e2e
       - name: Restart app - build new containers
         uses: appleboy/ssh-action@master
         with:
@@ -64,4 +97,3 @@ jobs:
             cd backend-fastapi &&
             git clone -b main https://github.com/mg-login-examples/login-frontend-vue.git frontend &&
             ./script.sh launch-app-dev-env
-# sudo ./script.sh launch-app
